[settings]
timeout = 1000

[relaychain]
default_image = "paritypr/polkadot-debug:master"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"

  [[relaychain.nodes]]
  name = "charlie"

  [[relaychain.nodes]]
  name = "dave"

[[parachains]]
id = 1000

  [[parachains.collators]]
  name = "collator01"
  command = "test-node"

  [[parachains.collators]]
  name = "collator02"
  command = "test-node"

[[parachains]]
id = 2000

  [[parachains.collators]]
  name = "collator03"
  command = "test-node"

  [[parachains.collators]]
  name = "collator04"
  command = "test-node"

[[parachains]]
id = 2001

  [[parachains.collators]]
  name = "collator05"
  command = "test-node"

  [[parachains.collators]]
  name = "collator06"
  command = "test-node"
