[package]
name = "tp-authorities-noting-inherent"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive", "max-encoded-len"] }
scale-info = { workspace = true }

test-relay-sproof-builder = { workspace = true, optional = true }
tp-core = { workspace = true, optional = true }

# Substrate
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-io = { workspace = true }
sp-trie = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true }

[features]
default = [ "std" ]
std = [
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-trie/std",
	"cumulus-primitives-core/std",
	"sp-io/std",
	"test-relay-sproof-builder/std",
	"tp-core/std"
]
