[package]
name = "tp-collator-assignment"
authors = []
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.1"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
hex-literal = { workspace = true }

log = { workspace = true }
serde = { workspace = true, optional = true, features = [ "derive" ] }

# Substrate
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true, optional = true }
sp-state-machine = { workspace = true, optional = true }
frame-support = { workspace = true, optional = true }
sp-trie = { workspace = true,  optional = true }

# Cumulus
cumulus-primitives-core = { workspace = true, optional = true }

# Polkadot
polkadot-primitives = {  workspace = true, optional = true }

[features]
default = [ "std" ]
std = [
	"parity-scale-codec/std",
	"serde/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime/std",
	"sp-state-machine/std",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"sp-trie/std",
	"polkadot-primitives"
]