[package]
name = "tp-collator-assignment"
authors = []
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.1"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
hex-literal = { workspace = true }

log = { workspace = true }
serde = { workspace = true, optional = true, features = [ "derive" ] }

# Substrate
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }

[features]
default = [ "std" ]
std = [
	"parity-scale-codec/std",
	"serde/std",
	"sp-core/std",
	"sp-std/std"
]