[package]
name = "tp-pooled-staking"
authors = []
description = "Primitives related to the Pooled Stacking pallet"
edition = "2021"
version = "0.1.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
frame-support = { workspace = true }
frame-system = { workspace = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
sp-api = { workspace = true }
sp-std = { workspace = true }
serde = { workspace = true, optional = true }

[features]
default = [ "std" ]
std = [
	"sp-api/std",
    "serde"
]
