[package]
name = "tp-construct-tanssi-runtime"
authors = { workspace = true }
description = "Macro to construct tanssi runtime with preconfigured pallets"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[dependencies]
impls = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }

pallet-timestamp = { workspace = true }
pallet-author-inherent = { workspace = true }
pallet-cc-authorities-noting = { workspace = true }

[features]
default = [ "std" ]
std = [
	"sp-core/std",
	"sp-runtime/std",
]
