name: Typescript tests
description: |
  Setup and run the typescript tests against a local tanssi node and templates.

inputs:
  frontier-template-binary:
    description: path to the frontier template binary
    required: true
  force-pass:
    description: "Indicate whether the workflow should mark the test step as successful, even if actual test failures occur."
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: "pnpm"
        cache-dependency-path: test/pnpm-lock.yaml
    - name: Set binary path and number of CPUs
      shell: bash
      run: |
        #### Ensure the frontier-template-binary binary is executable
        chmod uog+x ${{ inputs.frontier-template-binary}}

        cp ${{ inputs.frontier-template-binary}} target/release/

    - name: Install and run
      shell: bash
      run: |
        cd ./test
        pnpm install
        pnpm moonwall test dev_frontier_template || [[ '${{ inputs.force-pass }}' == 'true' ]]