[package]
name = "pallet-automation-time"
description = "Pallet for scheduling and running tasks in the future."
version = "1.0.0"
edition = "2021"
authors = ["OAK Developement Team"]
license = "GPL-3.0"
homepage = "https://oak.tech"
repository = 'https://github.com/OAK-Foundation/OAK-blockchain'
readme = 'README.md'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
parity-scale-codec= { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
log = { workspace = true }
hex = { workspace = true, features = ["alloc"] }

# Polkadot
# polkadot-parachain = { workspace = true }
staging-xcm = { package="xcm", workspace = true }

# Cumulus dependencies
cumulus-pallet-xcm = { workspace = true }
cumulus-primitives-core = { workspace = true }

# Substrate Dependencies
## Substrate Primitive Dependencies
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-io = { workspace = true }

## Substrate FRAME Dependencies
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }

## Substrate Pallet Dependencies
pallet-timestamp = { workspace = true }
pallet-balances = { workspace = true }

## Polkdadot deps
staging-xcm-builder = { package="xcm-builder", workspace = true }

## Local
# oak-primitives = { path = "../../oak-primitives", default-features = false }


[dev-dependencies]
rand = { workspace = true }
serde = { workspace = true }
sp-core = { workspace = true }

pallet-balances = { workspace = true }
pallet-xcm = { workspace = true }
staging-xcm-executor = { package="xcm-executor", workspace = true }

# Cumulus dependencies
parachain-info = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
  "frame-benchmarking",
]
try-runtime = ["frame-support/try-runtime"]
std = [
  "parity-scale-codec/std",
  "cumulus-pallet-xcm/std",
  "cumulus-primitives-core/std",
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-system/std",
  "pallet-timestamp/std",
  "pallet-xcm/std",
#  "polkadot-parachain/std",
  "scale-info/std",
  "sp-runtime/std",
  "sp-std/std",
  "staging-xcm/std",
  "staging-xcm-builder/std",
  "staging-xcm-executor/std",
]
dev-queue = []
