[package]
name = "pallet-collator-assignment"
version = "0.1.0"
description = "Collator assignment pallet"
authors = []
edition = "2021"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true, default-features = false, features = ["derive", "max-encoded-len"] }
scale-info = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
serde = { workspace = true, features = [ "derive" ], optional = true }
log = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
tp-collator-assignment = { workspace = true }

[dev-dependencies]
sp-io = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
    "serde",
	"tp-collator-assignment/std",
]
try-runtime = ["frame-support/try-runtime"]
