name: Typescript tests
description: |
  Setup and run the typescript tests against a local tanssi node and templates.

inputs:
  tanssi-binary:
    description: path to the tanssi binary
    required: true
  force-pass:
    description: "Indicate whether the workflow should mark the test step as successful, even if actual test failures occur."
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Set binary path and number of CPUs
      shell: bash
      run: |
        #### Ensure the tanssi binary is executable
        chmod uog+x ${{ inputs.tanssi-binary }}

        cp ${{ inputs.tanssi-binary}} target/release/

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: "pnpm"
        cache-dependency-path: test/pnpm-lock.yaml

    - name: Install typescript-api
      shell: bash
      run: |
        cd ./typescript-api
        pnpm install
        pnpm create-local-interfaces

    - name: Install and run
      shell: bash
      run: |
        cd ./test
        pnpm moonwall test dev_tanssi || [[ '${{ inputs.force-pass }}' == 'true' ]]