[package]
name = "tp-author-noting-inherent"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
log = { workspace = true }
hex-literal = { version = "0.3.4"}
parity-scale-codec = { workspace = true, default-features = false, features = ["derive", "max-encoded-len"] }
async-trait = { version = "0.1.63", optional = true }
scale-info = { version = "2.3.1", default-features = false, features = ["derive"] }
tracing = { version = "0.1.37", optional = true }

# Substrate
sc-client-api = { workspace = true, optional = true }
sp-api = { workspace = true, optional = true }
sp-core = { workspace = true, default-features = false }
sp-inherents = { workspace = true, default-features = false }
sp-runtime = { workspace = true, optional = true }
sp-state-machine = { workspace = true, optional = true }
sp-storage = { workspace = true, optional = true }
sp-consensus-aura = { workspace = true, optional = true }
sp-std = { workspace = true, optional = true }
sp-trie = { workspace = true, default-features = false }
frame-support = { workspace = true, optional = true }

# Cumulus
cumulus-primitives-core = { workspace = true, default-features = false }
cumulus-relay-chain-interface = { workspace = true, optional = true }
cumulus-pallet-parachain-system = { workspace = true, default-features = false }

polkadot-primitives = {  workspace = true, optional = true }

[features]
default = [ "std" ]
std = [
	"async-trait",
	"parity-scale-codec/std",
	"scale-info/std",
	"tracing",
	"sc-client-api",
	"sp-api",
	"sp-core/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-state-machine/std",
	"sp-std/std",
	"sp-storage",
	"sp-trie/std",
	"cumulus-primitives-core/std",
	"cumulus-relay-chain-interface",
	"polkadot-primitives",
	"frame-support",
	"sp-consensus-aura"
]
