[package]
name = "tp-author-noting-inherent"
version = "0.1.0"
authors = []
edition = "2021"

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive", "max-encoded-len"] }
async-trait = { workspace = true, optional = true }
scale-info = { workspace = true }

test-relay-sproof-builder = { workspace = true, optional = true }
tp-core = { workspace = true, optional = true }

# Substrate
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-runtime = { workspace = true, optional = true }
sp-state-machine = { workspace = true, optional = true }
sp-consensus-aura = { workspace = true, optional = true }
sp-std = { workspace = true }
sp-io = { workspace = true }
sp-trie = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true }
cumulus-relay-chain-interface = { workspace = true, optional = true }

[dev-dependencies]
cumulus-pallet-parachain-system = { workspace = true }
hex-literal = { workspace = true }


[features]
default = [ "std" ]
std = [
	"async-trait",
	"parity-scale-codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-runtime/std",
	"sp-state-machine/std",
	"sp-std/std",
	"sp-trie/std",
	"cumulus-primitives-core/std",
	"cumulus-relay-chain-interface",
	"sp-consensus-aura/std",
	"sp-io/std",
	"test-relay-sproof-builder/std",
	"tp-core/std",
]
