[package]
name = "pallet-author-noting"
version = "0.1.0"
description = "Author noting pallet"
authors = []
edition = "2021"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
hex-literal = "0.3.4"
parity-scale-codec = { workspace = true, default-features = false, features = ["derive", "max-encoded-len"] }
scale-info = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
serde = { workspace = true, features = [ "derive" ], optional = true }
log = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-consensus-aura = { workspace = true, default-features = false }
sp-inherents = { workspace = true, default-features = false }
sp-state-machine = { workspace = true, default-features = false }
sp-trie = { workspace = true, default-features = false }

cumulus-primitives-core = { workspace = true, default-features = false }
cumulus-pallet-parachain-system = { workspace = true, default-features = false }
tp-author-noting-inherent = { workspace = true, default-features = false }

[dev-dependencies]
sp-io = { workspace = true }
sp-version = { workspace = true }
sp-externalities = { workspace = true }
sp-state-machine = { workspace = true }
polkadot-parachain = {  workspace = true }
polkadot-primitives = {  workspace = true }

[features]
default = ["std"]
std = [
	"parity-scale-codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
    "serde",
    "sp-consensus-aura/std",
    "cumulus-primitives-core/std",
    "cumulus-pallet-parachain-system/std",
    "tp-author-noting-inherent/std",
    "sp-state-machine/std",
    "sp-trie/std"
]
try-runtime = ["frame-support/try-runtime"]
