name: Publish Typescript API
on:
  workflow_dispatch:
    inputs:
      sha:
        description: full sha to build the npm package from
        required: true

jobs:
  publish-typescript-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.sha }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Build typescript API
        run: |
          cd typescript-api
          npm install
          npm run build
      - name: Publish typescript API
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: typescript-api/build/package.json