name: Publish Runtime Draft

# The code (like generate-release-body) will be taken from the tag versions, not master
on:
  workflow_dispatch:
    inputs:
      from:
        description: tag (ex. runtime-53) to retrieve commit diff from
        required: true
      to:
        description: tag (ex. runtime-155) to generate release note and srtool runtimes from
        required: true

jobs:
  ####### Build runtimes with srtool #######

  setup-scripts:
    runs-on: bare-metal
    steps:
      - uses: actions/checkout@v3
      - name: Upload scripts
        uses: actions/upload-artifact@v3
        with:
          name: original-scripts
          path: scripts
      - name: Upload tools
        uses: actions/upload-artifact@v3
        with:
          name: original-tools
          path: tools

  build-srtool-runtimes:
    needs: ["setup-scripts"]
    runs-on: bare-metal
    strategy:
      matrix:
        chain: ["dancebox"]
        srtool_image:
          - purestake/srtool
        srtool_image_tag:
          - 1.69.0
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.to }}
      - name: Download original scripts
        uses: actions/download-artifact@v3
        with:
          name: original-scripts
          path: original-scripts
      - name: Build & Push purestake/srtool image
        if: github.repository == 'moondance-labs/tanssi'
        run: |
          docker pull "${{ matrix.srtool_image }}:${{ matrix.srtool_image_tag }}" && image_exists=true || image_exists=false

          if [[ $image_exists = "false" ]]; then
            echo building "${{ matrix.srtool_image }}:${{ matrix.srtool_image_tag }}"
            docker build --pull --no-cache . \
              -f docker/moonbeam-srtool.Dockerfile \
              --build-arg SRTOOL_IMAGE_TAG=${{ matrix.srtool_image_tag }} \
              -t ${{ matrix.srtool_image }}:${{ matrix.srtool_image_tag }}

            echo pushing "${{ matrix.srtool_image }}:${{ matrix.srtool_image_tag }}"
            docker push "${{ matrix.srtool_image }}:${{ matrix.srtool_image_tag }}"
          else
            echo skiping build "${{ matrix.srtool_image }}:${{ matrix.srtool_image_tag }}", image already exists
          fi