name: CI

on: ["pull_request"]

jobs:
  set-tags:
    runs-on: ubuntu-latest
    outputs:
      polkadot_release: ${{ steps.get-polkadot-release-tag.outputs.polkadot_release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.sha }}
      - name: Get polkadot release tag
        id: get-polkadot-release-tag
        run: |
          branch=$(egrep -o '/polkadot.*#([^\"]*)' Cargo.lock | head -1 | sed 's/.*release-//#')
          echo "polkadot_release=$(echo $branch | sed 's/#.*//')" >> $GITHUB_OUTPUT
      - name: Display variables
        run: |
          echo polkadot_release: ${{ steps.get-polkadot-release-tag.outputs.polkadot_release }}
  ####### Building and Testing binaries #######
  build:
    runs-on: self-hosted
    env:
      RUSTFLAGS: "-C opt-level=3 -D warnings"
      TMP_TARGET: "/tmp/target"
      CARGO_TARGET_DIR: "target"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        run: rustup show

      - name: Install nightly
        run: rustup install nightly-2022-11-14
      
      - name: Add wasm32-unknown-unknown to nightly
        run: rustup target add wasm32-unknown-unknown --toolchain nightly-2022-11-14

      - name: Formatter
        run: cargo fmt --all --check

      - name: Build
        run: cargo build --release --all

      - name: Create chain specs
        run: |
          mkdir specs
          ./target/release/container-chain-template-simple-node build-spec --disable-default-bootnode --parachain-id 2000 --seeds "Collator2000-01,Collator2000-02" --raw > specs/template-container-2000.json
          ./target/release/container-chain-template-simple-node build-spec --disable-default-bootnode --parachain-id 2001 --seeds "Collator2001-01,Collator2001-02" --raw > specs/template-container-2001.json
          ./target/release/test-node build-spec --parachain-id 1000 --add-container-chain specs/template-container-2000.json --add-container-chain specs/template-container-2001.json > specs/tanssi-1000.json

      - name: Test
        run: cargo test --release --all

      - name: Save runtime wasm
        run: |
          mkdir -p runtimes
          cp $CARGO_TARGET_DIR/release/wbuild/container-chain-template-simple-runtime/container_chain_template_simple_runtime.compact.wasm runtimes/;
          cp $CARGO_TARGET_DIR/release/wbuild/test-runtime/test_runtime.compact.compressed.wasm runtimes/;

      - name: Upload runtimes
        uses: actions/upload-artifact@v3.1.2
        with:
          name: runtimes
          path: runtimes

      - name: Save tanssi and template binaries
        run: |
          mkdir -p binaries
          cp $CARGO_TARGET_DIR/release/test-node binaries/test-node;
          cp $CARGO_TARGET_DIR/release/container-chain-template-simple-node binaries/container-chain-template-simple-node;

      - name: Upload binary
        uses: actions/upload-artifact@v3.1.2
        with:
          name: binaries
          path: binaries
      
  typescript-tests:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.sha }}
        
      - name: Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
        
      - name: Node  
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "pnpm"
          cache-dependency-path: test/pnpm-lock.yaml

      - name: "Download binaries"
        uses: actions/download-artifact@v3.0.2
        with:
          name: binaries
          path: target/release
      
      - name: "Install and run upgrade test"
        run: |
          chmod uog+x target/release/test-node
          cd test
          pnpm i
          pnpm moonwall test dev_tanssi

  zombienet-tests:
    runs-on: ubuntu-latest
    needs: ["set-tags", "build"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.sha }}

      - name: Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
        
      - name: Node  
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"
          cache-dependency-path: test/pnpm-lock.yaml

      - name: "Download binaries"
        uses: actions/download-artifact@v3.0.2
        with:
          name: binaries
          path: test/tmp

      
      - name: Retrieve polkadot binary from docker
        run: |
          POLKADOT_RELEASE=${{ needs.set-tags.outputs.polkadot_release }}
          DOCKER_TAG="parity/polkadot:$POLKADOT_RELEASE"
          echo $DOCKER_TAG
          echo $POLKADOT_RELEASE
          docker rm -f dummy 2> /dev/null | true
          docker create -ti --name dummy $DOCKER_TAG bash
          docker cp dummy:/usr/bin/polkadot test/tmp/polkadot
          docker rm -f dummy
      
      - name: "Run zombie test"
        run: |
          cd test
          pnpm i

          chmod uog+x tmp/test-node
          chmod uog+x tmp/container-chain-template-simple-node
          chmod uog+x tmp/polkadot

          ## Generate specs
          tmp/container-chain-template-simple-node build-spec --parachain-id 2000 --seeds "Collator2000-01,Collator2000-02" --raw --> tmp/template-container-2000.json
          tmp/container-chain-template-simple-node build-spec --parachain-id 2001 --seeds "Collator2001-01,Collator2001-02" --raw --> tmp/template-container-2001.json

          ## Run tests

          pnpm moonwall test zombie_tanssi_ci
