name: CI

on: ["pull_request"]

jobs:

  ####### Building and Testing binaries #######

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust toolchain
        run: rustup show

      - name: Formatter
        run: cargo fmt --all --check

      - name: Build container chain template
        run: cargo build --release -p container-chain-template-node

      - name: mkdir specs
        run: mkdir specs

      - name: Generate container chain template chain spec 2000
        run: ./target/release/container-chain-template-node build-spec --disable-default-bootnode --parachain-id 2000 --seeds "Collator2000-01,Collator2000-02" --raw > specs/template-container-2000.json

      - name: Generate container chain template chain spec 2001
        run: ./target/release/container-chain-template-node build-spec --disable-default-bootnode --parachain-id 2001 --seeds "Collator2001-01,Collator2001-02" --raw > specs/template-container-2001.json

      - name: Build all
        run: cargo build --release --all

      - name: Test all
        run: cargo test --release --all
      
      - name: Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      
      - name: Node  
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
          cache-dependency-path: test/pnpm-lock.yaml
      
      - name: "Install and run upgrade test"
        run: |
          cd test
          pnpm i
          pnpm moonwall test dev_tanssi
