name: Upgrade typescript API
on:
  workflow_dispatch:
    inputs:
      spec_version:
        description: runtime spec version (ex. 1601)
        required: true

jobs:
  upgrading-typescript-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
        with:
          fetch-depth: 0
      - name: Retrieve tanssi binary
        run: |
          COMMIT=`git rev-list -n 1 '${{ github.event.inputs.spec_version }}'`
          echo "FINISHED"
          SHA=sha-${COMMIT::8}
          DOCKER_TAG="moondancelabs/tanssi:$SHA"
          
          # Clear the dummy container if it wasn't properly cleaned up
          docker rm -f dummy 2> /dev/null
          docker create -ti --name dummy $DOCKER_TAG bash
          mkdir -p target/release
          docker cp dummy:/tanssi/tanssi-node target/release/tanssi-node
          docker rm -f dummy
          ls target/release/
      - name: Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Upgrade polkadotjs for typescript-api
        run: |
          ls target/release
          cd typescript-api
          pnpm add @polkadot/api@latest
          pnpm add @polkadot/api-derive@latest
          pnpm add @polkadot/api-augment@latest
          pnpm add @polkadot/api-base@latest
          pnpm add @polkadot/rpc-augment@latest
          pnpm add @polkadot/rpc-core@latest
          pnpm add @polkadot/rpc-provider@latest
          pnpm add @polkadot/types-create@latest
          pnpm add @polkadot/types-augment@latest
          pnpm add @polkadot/types-support@latest
          pnpm add @polkadot/types-codec@latest
          pnpm add @polkadot/types@latest
          pnpm add @polkadot/types-known@latest
          pnpm run build
      - name: regenerate typescript api with new runtime metadata
        run: |
          cd typescript-api
          ./scripts/runtime-upgrade.sh ${{ github.event.inputs.spec_version }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: master
          branch: "typescript-api-${{ github.event.inputs.spec_version }}"
          commit-message: typescript API v0.${{ github.event.inputs.spec_version }}.0"
          draft: true
          title: "Upgrade typescript API for runtime  ${{ github.event.inputs.spec_version }}"
          reviewers: "librelois,crystalin"
          labels: "B0-silent,D2-notlive"